name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install picotool
        run: |
          sudo apt update
          sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libstdc++-arm-none-eabi-newlib
          mkdir -p  ~/pico
          cd ~/pico/
          git clone -b master https://github.com/raspberrypi/pico-sdk.git
          cd pico-sdk
          git submodule update --init
          echo 'export PICO_SDK_PATH=$HOME/pico/pico-sdk' >> $GITHUB_PATH
          
      - name: Install Rust thumbv8m.main-none-eabihf Target
        run: |
          rustup target add thumbv8m.main-none-eabihf
          
      - name: Install probe-rs
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/probe-rs/probe-rs/releases/latest/download/probe-rs-tools-installer.sh | sh

      - name: Build (release)
        run: cargo build --release
      
